"""Public transport-neutral BoberAgent protocol surface."""

from .errors import (
    ConflictingInvocation,
    MalformedMessage,
    ProtocolError,
    TransportBackpressure,
    TransportDisconnected,
    TransportError,
    UnknownNode,
    UnsupportedProtocolVersion,
)
from .interfaces import CapabilityTransport, TransportNodeEndpoint
from .memory import InMemoryTransport
from .models import (
    TRANSPORT_PROTOCOL_VERSION,
    AssetProjection,
    DeliveryAcknowledgement,
    DeliveryKind,
    EventEnvelope,
    HandshakeRequest,
    InvocationDelivery,
    InvocationEnvelope,
    MissionProjection,
    NodeAdvertisement,
    OutboundEnvelope,
    ResultEnvelope,
    TransportFailure,
    TransportMessageId,
    ensure_supported_protocol,
    event_message_id,
    invocation_fingerprint,
    invocation_message_id,
    parse_acknowledgement,
    parse_advertisement,
    parse_handshake_request,
    parse_invocation,
    parse_outbound,
    result_message_id,
    serialize_message,
)

__all__ = [
    "TRANSPORT_PROTOCOL_VERSION",
    "AssetProjection",
    "CapabilityTransport",
    "ConflictingInvocation",
    "DeliveryAcknowledgement",
    "DeliveryKind",
    "EventEnvelope",
    "HandshakeRequest",
    "InMemoryTransport",
    "InvocationDelivery",
    "InvocationEnvelope",
    "MalformedMessage",
    "MissionProjection",
    "NodeAdvertisement",
    "OutboundEnvelope",
    "ProtocolError",
    "ResultEnvelope",
    "TransportBackpressure",
    "TransportDisconnected",
    "TransportError",
    "TransportFailure",
    "TransportMessageId",
    "TransportNodeEndpoint",
    "UnknownNode",
    "UnsupportedProtocolVersion",
    "ensure_supported_protocol",
    "event_message_id",
    "invocation_fingerprint",
    "invocation_message_id",
    "parse_acknowledgement",
    "parse_advertisement",
    "parse_handshake_request",
    "parse_invocation",
    "parse_outbound",
    "result_message_id",
    "serialize_message",
]
