"""Deterministic Knowledge and optional derived semantic discovery owned by Core."""

from .chunking import CHUNKING_VERSION, EMBEDDING_INPUT_VERSION, chunk_source
from .markdown import CuratedMarkdownLoader, KnowledgeSourceError
from .models import (
    KnowledgeDocument,
    KnowledgeId,
    KnowledgeSourceKind,
    KnowledgeStatus,
    MarkdownHeading,
    ProcedureDefinition,
    ProcedureId,
    ProcedureStep,
    SourceProvenance,
)
from .openai_embeddings import EmbeddingHTTPConfiguration, OpenAICompatibleEmbeddingProvider
from .procedures import ProcedureRegistry
from .repository import KnowledgeConflict, KnowledgeRepository
from .router import (
    KnowledgeRequest,
    KnowledgeResolution,
    KnowledgeRoute,
    KnowledgeRouter,
    UnsupportedKnowledgeRoute,
)
from .semantic import (
    EmbeddingAuthenticationError,
    EmbeddingBatch,
    EmbeddingConfigurationError,
    EmbeddingDimensionError,
    EmbeddingError,
    EmbeddingProvider,
    EmbeddingResponseError,
    EmbeddingUnavailableError,
    IndexManifest,
    SemanticChunk,
    SemanticFilters,
    SemanticHit,
    SemanticIndex,
    SemanticIndexIncompatible,
    SemanticIndexStale,
    SemanticRetrievalService,
    SemanticUnavailable,
)

__all__ = [
    "CHUNKING_VERSION",
    "EMBEDDING_INPUT_VERSION",
    "CuratedMarkdownLoader",
    "EmbeddingAuthenticationError",
    "EmbeddingBatch",
    "EmbeddingConfigurationError",
    "EmbeddingDimensionError",
    "EmbeddingError",
    "EmbeddingHTTPConfiguration",
    "EmbeddingProvider",
    "EmbeddingResponseError",
    "EmbeddingUnavailableError",
    "IndexManifest",
    "KnowledgeConflict",
    "KnowledgeDocument",
    "KnowledgeId",
    "KnowledgeRepository",
    "KnowledgeRequest",
    "KnowledgeResolution",
    "KnowledgeRoute",
    "KnowledgeRouter",
    "KnowledgeSourceError",
    "KnowledgeSourceKind",
    "KnowledgeStatus",
    "MarkdownHeading",
    "OpenAICompatibleEmbeddingProvider",
    "ProcedureDefinition",
    "ProcedureId",
    "ProcedureRegistry",
    "ProcedureStep",
    "SemanticChunk",
    "SemanticFilters",
    "SemanticHit",
    "SemanticIndex",
    "SemanticIndexIncompatible",
    "SemanticIndexStale",
    "SemanticRetrievalService",
    "SemanticUnavailable",
    "SourceProvenance",
    "UnsupportedKnowledgeRoute",
    "chunk_source",
]
